# Generated by Django 5.2.16 on 2026-08-03 00:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_user_id', models.BigIntegerField(db_column='github_user_id', unique=True)),
                ('github_login', models.CharField(db_column='github_login', max_length=100)),
                ('access_token', models.TextField(db_column='access_token')),
                ('token_type', models.CharField(blank=True, db_column='token_type', max_length=50, null=True)),
                ('scope', models.CharField(blank=True, db_column='scope', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'github_auth',
            },
        ),
    ]
