# Generated by Django 5.2.16 on 2026-08-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_column='user_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED_PROVIDER', 'Failed Provider'), ('FAILED_VALIDATION', 'Failed Validation'), ('FAILED_TIMEOUT', 'Failed Timeout')], max_length=32)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'generation_log',
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='generation__user_id_b9cfc5_idx')],
            },
        ),
    ]
