# Generated by Django 5.2.16 on 2026-08-03 00:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_name', models.CharField(db_column='repo_name', max_length=200)),
                ('repo_url', models.CharField(db_column='repo_url', max_length=500)),
                ('default_branch', models.CharField(blank=True, db_column='default_branch', max_length=100, null=True)),
                ('pages_enabled', models.BooleanField(db_column='pages_enabled', default=False)),
                ('pages_url', models.CharField(blank=True, db_column='pages_url', max_length=500, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, db_column='last_published_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'published_portfolio',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('dist_path', models.CharField(db_column='dist_path', max_length=500)),
                ('data_path', models.CharField(db_column='data_path', max_length=100)),
                ('portfolio_filename', models.CharField(db_column='portfolio_filename', max_length=100)),
                ('style_filename', models.CharField(db_column='style_filename', max_length=100)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'template',
                'indexes': [models.Index(fields=['is_active'], name='template_is_acti_51d468_idx')],
            },
        ),
    ]
